### ISSUE TITLE
Weird compilation error

### ISSUE THREAD

**Issue by livingsilver94** [tarkah/dopt#2]
Consider this repository and this commit: https://github.com/serpent-os/boulder/commit/d72bb75db65c25b20ce65338e20fb96936dd925a

If you build it with `dub build boulder:container`, you'll see

> ../../../.dub/packages/dopt/c90d16a/dopt/source/dopt/parse.d(336,34): Error: none of the overloads of template `dopt.parse.subcommand` are callable using argument types `!()(ContainerCLI)`
> ../../../.dub/packages/dopt/c90d16a/dopt/source/dopt/parse.d(311,28):        Candidate is: `subcommand(T)(ref T t, ref string[] args, string[] path)`
> ../../../.dub/packages/dopt/c90d16a/dopt/source/dopt/parse.d(105,24): Error: template instance `dopt.parse.subcommand!(ContainerCLI)` error instantiating
> ../../../.dub/packages/dopt/c90d16a/dopt/source/dopt/parse.d(62,19):        instantiated from here: `parseArgs!(ContainerCLI)`
> source/container/cli/package.d(45,15):        instantiated from here: `parse!(ContainerCLI)`

But if you apply this patch:

```diff
diff --git a/source/container/cli/package.d b/source/container/cli/package.d
index 4e079f0..3235cea 100644
--- a/source/container/cli/package.d
+++ b/source/container/cli/package.d
@@ -34,7 +34,7 @@ public struct ContainerCLI
     string path = null;
 
     @Subcommand()
-    Subcommands commands;
+    Subcommands subcommand;


 }
```

It builds! Do fields have to be prefixed by their type name?

**Comment by tarkah** [comment]
Thanks! I was hardcoding that field name instead of using the user provided field name :P
