### ISSUE TITLE
How to escape flags?

### ISSUE THREAD

**Issue by livingsilver94** [tarkah/dopt#5]
Suppose I have:

```dlang
@Command() @Help("Run a command in an existing container")
package struct Run {
    @Positional() @Help("Command to run, with arguments")
    string[] args;
}
```

I want to pass `./mycommand run /bin/bash --login`. Currently I get in return `Unrecognized option --login`.

How can I tell dopt the `--login` flag is part of the `args` array? `./mycommand run -- /bin/bash --login` doesn't work either.

**Comment by tarkah** [comment]
I need to add support for this, should be easy
